(function () {
    'use strict';
    angular.module('nomumo').config(function ($translateProvider) {

        $translateProvider.translations('de_DE', {
            LAN:            'Sprache',
            LAN_DE:         'Deutsch',
            LAN_ENG:        'Englisch',
            LAN_EO:         'Esperanto',
            NAV_NEW_POLL:   'Neue Umfrage',
            NAV_ABOUT:      'Über',
            TITLE_POLLDETAILS:  'Umfragedetails',
            TITLE_DATE:     'Datum',
            TITLE_TIME:     'Uhrzeit',
            FORM_TITLE:     'Titel',
            FORM_LOCATION:  'Ort',
            FORM_DESCRIPTION:   'Beschreibung',
            FORM_NAME:          'Name',
            FORM_EMAIL:         'E-Mail',
            FORM_POLL_MODE:     'Umfragemodus',
            FORM_POLL_MODE0:    'Ja-Nein',
            FORM_POLL_MODE1:    'Ja-(Ja)-Nein',
            FORM_POLL_MODE2:    'Ja-Vielleicht-Nein',
            BUTTON_NEXT_STEP:   'Nächster Schritt',
            FORM_DATE_TEXT:     'Bitte wählen Sie die Tage für die Umfrage',
            FORM_DATE_DELETE:   'Löschen',
            FORM_DATE_DATE:     'Datum',
            FORM_TIME_TEXT:     'Bitte wählen Sie die Uhrzeiten für die jeweiligen Daten',
            FORM_TIME_TIME:     'Zeit',
            FORM_TIME_ADD_FIELD:    'Feld hinzufügen',
            FORM_TIME_CREATE_POLL:  'Umfrage erstellen',
            CREATED_TEXT:       'Die Umfrage wurde erfolgreich erstellt und ist ab sofort unter folgender Adresse erreichbars:',
            CREATED_CLIPBOARD:  'Link in Zwischenablage kopieren',
            POLL_FROM:          'Umfrage von',
            POLL_LOCATION:      'Ort:',
            POLL_SAVE:          'Speichern',
            POLL_COMMENT:       'Kommentar',
            POLL_ADD_COMMENT:   'Kommentar hinzufügen',
            POLL_NAME:          'Name',
            POLL_EMAIL_OPT:     'E-Mail (optional)',
            POLL_SAVE_COMMENT:  'Kommentar speichern',
            POLL_DELETE:        'Löschen',
            POLL_EDIT:          'Bearbeiten',
            POLL_INFOMESSAGE1:  '*Mit dem Eintragen Ihrer E-Mail-Adresse werden Sie über Änderungen an der Umfrage und neue Kommentare informiert.',
            POLL_INFOMESSAGE2:  '**Aus Datenschutzgründen wird Ihre E-Mail-Adresse nach dem Speichern nicht im Browser angezeigt, kann jedoch überschrieben werden.',
            POLL_YES:           'Ja',
            POLL_NO:            'Nein',
            POLL_YES2:          '(Ja)',
            POLL_MAYBE:         'Vielleicht'
        });

        $translateProvider.translations('en_US', {
            LAN:            'Language',
            LAN_DE:         'German',
            LAN_ENG:        'English',
            LAN_EO:         'Esperanto',
            NAV_NEW_POLL:   'New Poll',
            NAV_ABOUT:      'About',
            TITLE_POLLDETAILS:  'Details',
            TITLE_DATE:     'Date',
            TITLE_TIME:     'Time',
            FORM_TITLE:     'Title',
            FORM_LOCATION:  'Location',
            FORM_DESCRIPTION:   'Description',
            FORM_NAME:          'Name',
            FORM_EMAIL:         'E-Mail',
            FORM_POLL_MODE:     'Poll mode',
            FORM_POLL_MODE0:    'Yes-No',
            FORM_POLL_MODE1:    'Yes-(Yes)-No',
            FORM_POLL_MODE2:    'Yes-Maybe-No',
            BUTTON_NEXT_STEP:   'Next Step',
            FORM_DATE_TEXT:     'Please select the days for the poll',
            FORM_DATE_DELETE:   'Delete',
            FORM_DATE_DATE:     'Date',
            FORM_TIME_TEXT:     'Please enter the times for the dates',
            FORM_TIME_TIME:     'Time',
            FORM_TIME_ADD_FIELD:    'Add field',
            FORM_TIME_CREATE_POLL:  'Create poll',
            CREATED_TEXT:       'The poll was created successfully. You can reach the poll under:',
            CREATED_CLIPBOARD:  'Copy link into clipboard',
            POLL_FROM:          'Poll from',
            POLL_LOCATION:      'Location:',
            POLL_SAVE:          'Save',
            POLL_COMMENT:       'Comment',
            POLL_ADD_COMMENT:   'Add comment',
            POLL_NAME:          'Name',
            POLL_EMAIL_OPT:     'E-Mail (optional)',
            POLL_SAVE_COMMENT:  'Save comment',
            POLL_DELETE:        'Delete',
            POLL_EDIT:          'Edit',
            POLL_INFOMESSAGE1:  '*By entering your email address you will be informed about changes in the poll and new comments.',
            POLL_INFOMESSAGE2:  '**For privacy reasons your email address will not be displayed in the browser after saving but can be overridden.',
            POLL_YES:           'Yes',
            POLL_NO:            'No',
            POLL_YES2:          '(Yes)',
            POLL_MAYBE:         'Maybe'
        });

        $translateProvider.translations('eo', {
            LAN:            			'Lingvo',
            LAN_DE:         			'Germana',
            LAN_ENG:        			'Angla',
            LAN_EO:                     'Esperanto',
            NAV_NEW_POLL:   			'Nova enketo',
            NAV_ABOUT:      			'Pri',
            TITLE_POLLDETAILS:  		'Enketdetaloj',
            TITLE_DATE:     			'Dato',
            TITLE_TIME:     			'Tempo',
            FORM_TITLE:     			'Titolo',
            FORM_LOCATION:  			'Loko',
            FORM_DESCRIPTION:   		'Priskribo',
            FORM_NAME:          		'Nomo',
            FORM_EMAIL:         		'Emajlo',
            FORM_POLL_MODE:     		'Enketspeco',
            FORM_POLL_MODE0:    		'Jes-Ne',
            FORM_POLL_MODE1:    		'Jes-(Jes)-Ne',
            FORM_POLL_MODE2:    		'Jes-Eble-Ne',
            BUTTON_NEXT_STEP:   		'Sekva pasxo',
            FORM_DATE_TEXT:     		'Bonvolu elekti la tagojn por la enketo.',
            FORM_DATE_DELETE:   		'Nuligi',
            FORM_DATE_DATE:     		'Dato',
            FORM_TIME_TEXT:     		'Bonvolu elekti la horo por la datojn',
            FORM_TIME_TIME:     		'Tempo',
            FORM_TIME_ADD_FIELD:    	'Aldoni kampo',
            FORM_TIME_CREATE_POLL:  	'Kreari enketo',
            CREATED_TEXT:       		'La enketo sukcesa estas kreita kaj estas atingebla apud la adreso:',
            CREATED_CLIPBOARD:  		'Kopii la Ligilo en tondujon',
            POLL_FROM:          		'Enketo de',
            POLL_LOCATION:      		'Loko:',
            POLL_SAVE:          		'Konservi',
            POLL_COMMENT:       		'Komento',
            POLL_ADD_COMMENT:   		'Aldoni komenton',
            POLL_NAME:          		'Nomo',
            POLL_EMAIL_OPT:     		'Emajlo (laŭvola)',
            POLL_SAVE_COMMENT:  		'Konservi komenton',
            POLL_DELETE:        		'Nuligi',
            POLL_EDIT:          		'Redakti',
            POLL_INFOMESSAGE1:  		'*Se oni aldonas la emajladreson, oni estas informota pri novajn komentojn kaj sxangxojn de la enkto.',
            POLL_INFOMESSAGE2:  		'**Pro privateco kialoj, via emajladreso ne estas videbla en la retumilo post la konservado, sed gxi povas esti anstatauigita.',
            POLL_YES:           		'Jes',
            POLL_NO:            		'Ne',
            POLL_YES2:          		'(Jes)',
            POLL_MAYBE:         		'Eble'
        });


        $translateProvider.preferredLanguage('de_DE');
        $translateProvider.useSanitizeValueStrategy(null);
    });
})();
